This notebook is started to collect the data needed for my Capstone Project

## Imports

In [231]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from time import sleep
from datetime import datetime

from selenium import webdriver

# Pro Football Reference

In [90]:
# Making request to the website
url = 'https://www.pro-football-reference.com/years/2018/'
res = requests.get(url)
res.status_code

200

In [91]:
soup = BeautifulSoup(res.content, 'lxml')

## 2018 Wins/Losses

## AFC Teams

In [92]:
AFC_table = soup.find('table', {'id': 'AFC'})

In [95]:
teams = []
for row in AFC_table.find_all('tr')[1:]:
    team = {}
    tm = row.find('th')
    wins = row.find('td', {'data-stat': 'wins'})
    loss = row.find('td', {'data-stat': 'losses'})
    tie = row.find('td', {'data-stat': 'ties'})
    wlp = row.find('td', {'data-stat': 'win_loss_perc'})
    pts = row.find('td', {'data-stat': 'points'})
    ptsA = row.find('td', {'data-stat': 'points_opp'})
    dpts = row.find('td', {'data-stat': 'points_diff'})
    moV = row.find('td', {'data-stat': 'mov'})
    sos = row.find('td', {'data-stat': 'sos_total'})
    srs = row.find('td', {'data-stat': 'srs_total'})
    osrs = row.find('td', {'data-stat': 'srs_offense'})
    dsrs = row.find('td', {'data-stat': 'srs_defense'})
    
    
    
                   
    if tm:
        team['team'] = tm.text.replace('*','').replace('+','')
        team['year'] = 2018
    if wins:
        team['wins'] = wins.text
    if loss:
        team['losses'] = loss.text
    if tie:
        team['ties'] = tie.text
    if wlp:
        team['win_loss_perc'] = wlp.text
    if pts:
        team['points_scored'] = pts.text
    if ptsA:
        team['opp_points'] = ptsA.text
    if dpts:
        team['points_diff'] = dpts.text
    if moV:
        team['margin_of_victory'] = moV.text
    if sos:
        team['SoS'] = sos.text 
    if srs:
        team['SRS'] = srs.text
    if osrs:
        team['OSRS'] = osrs.text
    if dsrs:
        team['DSRS'] = dsrs.text
    
    
    else:
        continue
    
    teams.append(team)
AFC_df = pd.DataFrame(teams)

In [96]:
AFC_df

,team,year,wins,losses,ties,win_loss_perc,points_scored,opp_points,points_diff,margin_of_victory,SoS,SRS,OSRS,DSRS
0,New England Patriots,2018,11,5,0,.688,436,325,111,6.9,-1.8,5.2,3.1,2.1
1,Miami Dolphins,2018,7,9,0,.438,319,433,-114,-7.1,-1.7,-8.8,-3.6,-5.2
2,Buffalo Bills,2018,6,10,0,.375,269,374,-105,-6.6,-0.3,-6.9,-6.3,-0.6
3,New York Jets,2018,4,12,0,.250,333,441,-108,-6.8,-1.1,-7.8,-2.0,-5.9
4,Baltimore Ravens,2018,10,6,0,.625,389,287,102,6.4,0.6,7.0,0.6,6.4
5,Pittsburgh Steelers,2018,9,6,1,.594,428,360,68,4.3,1.3,5.6,3.9,1.7
6,Cleveland Browns,2018,7,8,1,.469,359,392,-33,-2.1,1.7,-0.3,-1.0,0.6
7,Cincinnati Bengals,2018,6,10,0,.375,368,455,-87,-5.4,2.0,-3.4,0.0,-3.4
8,Houston Texans,2018,11,5,0,.688,402,316,86,5.4,-1.5,3.8,2.4,1.4
9,Indianapolis Colts,2018,10,6,0,.625,433,344,89,5.6,-2.2,3.4,3.9,-0.6
10,Tennessee Titans,2018,9,7,0,.563,310,303,7,0.4,-0.2,0.2,-3.2,3.5
11,Jacksonville Jaguars,2018,5,11,0,.313,245,316,-71,-4.4,0.4,-4.0,-8.1,4.0
12,Kansas City Chiefs,2018,12,4,0,.750,565,421,144,9.0,-0.1,8.9,12.6,-3.8
13,Los Angeles Chargers,2018,12,4,0,.750,428,329,99,6.2,-0.2,6.0,3.0,2.9
14,Denver Broncos,2018,6,10,0,.375,329,349,-20,-1.3,0.7,-0.5,-3.6,3.1
15,Oakland Raiders,2018,4,12,0,.250,290,467,-177,-11.1,1.8,-9.3,-5.2,-4.1

## NFC Teams

In [7]:
NFC_table = soup.find('table', {'id': 'NFC'})

In [8]:
teams = []
for row in NFC_table.find_all('tr')[1:]:
    team = {}
    tm = row.find('th')
    wins = row.find('td', {'data-stat': 'wins'})
    loss = row.find('td', {'data-stat': 'losses'})
    tie = row.find('td', {'data-stat': 'ties'})
    wlp = row.find('td', {'data-stat': 'win_loss_perc'})
    pts = row.find('td', {'data-stat': 'points'})
    ptsA = row.find('td', {'data-stat': 'points_opp'})
    dpts = row.find('td', {'data-stat': 'points_diff'})
    moV = row.find('td', {'data-stat': 'mov'})
    sos = row.find('td', {'data-stat': 'sos_total'})
    srs = row.find('td', {'data-stat': 'srs_total'})
    osrs = row.find('td', {'data-stat': 'srs_offense'})
    dsrs = row.find('td', {'data-stat': 'srs_defense'})
    
    
    
                   
    if tm:
        team['team'] = tm.text.replace('*','').replace('+','')
    if wins:
        team['wins'] = wins.text
    if loss:
        team['losses'] = loss.text
    if tie:
        team['ties'] = tie.text
    if wlp:
        team['win_loss_perc'] = wlp.text
    if pts:
        team['points_scored'] = pts.text
    if ptsA:
        team['opp_points'] = ptsA.text
    if dpts:
        team['points_diff'] = dpts.text
    if moV:
        team['margin_of_victory'] = moV.text
    if sos:
        team['SoS'] = sos.text 
    if srs:
        team['SRS'] = srs.text
    if osrs:
        team['OSRS'] = osrs.text
    if dsrs:
        team['DSRS'] = dsrs.text
    
    
    else:
        continue
    
    teams.append(team)
NFC_df = pd.DataFrame(teams)

In [9]:
NFC_df

,team,wins,losses,ties,win_loss_perc,points_scored,opp_points,points_diff,margin_of_victory,SoS,SRS,OSRS,DSRS
0,Dallas Cowboys,10,6,0,.625,339,324,15,0.9,0.2,1.1,-1.9,2.9
1,Philadelphia Eagles,9,7,0,.563,367,348,19,1.2,0.5,1.7,0.0,1.8
2,Washington Redskins,7,9,0,.438,281,359,-78,-4.9,-0.1,-4.9,-5.6,0.6
3,New York Giants,5,11,0,.313,369,412,-43,-2.7,0.5,-2.2,0.8,-2.9
4,Chicago Bears,12,4,0,.750,421,283,138,8.6,-2.3,6.3,1.5,4.8
5,Minnesota Vikings,8,7,1,.531,360,341,19,1.2,-0.6,0.6,-1.2,1.8
6,Green Bay Packers,6,9,1,.406,376,400,-24,-1.5,-1.2,-2.7,0.0,-2.7
7,Detroit Lions,6,10,0,.375,324,360,-36,-2.3,-0.8,-3.0,-3.3,0.3
8,New Orleans Saints,13,3,0,.813,504,353,151,9.4,0.6,10.1,7.9,2.2
9,Atlanta Falcons,7,9,0,.438,414,423,-9,-0.6,0.4,-0.1,2.5,-2.6
10,Carolina Panthers,7,9,0,.438,376,382,-6,-0.4,1.3,0.9,0.1,0.8
11,Tampa Bay Buccaneers,5,11,0,.313,396,464,-68,-4.3,1.7,-2.6,2.0,-4.6
12,Los Angeles Rams,13,3,0,.813,527,384,143,8.9,-0.4,8.5,9.5,-1.1
13,Seattle Seahawks,10,6,0,.625,428,347,81,5.1,-0.6,4.5,3.0,1.5
14,San Francisco 49ers,4,12,0,.250,342,435,-93,-5.8,0.3,-5.5,-2.5,-3.1
15,Arizona Cardinals,3,13,0,.188,225,425,-200,-12.5,1.0,-11.5,-9.6,-1.9

## 2018 Offensive Stats

In [77]:
pass_table_18 = soup.find('table', {'id': 'passing'})
pass_table_18

In [74]:
pass_table_18.find_all('tr')

AttributeError: 'NoneType' object has no attribute 'find_all'

This error is due to the page in this section being loaded by Javascript so the contents can not be found. I will use Selenium instead to help with this issue to access this content. Also selenium may help with automating the scraping process by gathering the content link by link.

In [8]:
# for child in pass_table_18.children:
#     print(child)

# Selenium Solution

In [296]:
# Link to the main page
surl = 'https://www.pro-football-reference.com/years/'

In [353]:
driver = webdriver.Chrome(executable_path="./chromedriver/macos/chromedriver")
driver.get(surl)

In [354]:
soup = BeautifulSoup(driver.page_source)

### Testing code out to include in the loop

In [129]:
year_link = driver.find_element_by_link_text('2018')
year_link.click()

In [130]:
soup_18 = BeautifulSoup(driver.page_source)

In [77]:
seasons_button = driver.find_element_by_link_text('Seasons')
seasons_button.click()

In [131]:
# This is the code to find the passing table in the specific NFL year.
pass_table_18 = soup_18.find('table', {'id': 'passing'})

In [171]:
pass_table_18.find_all('tr')[1]

'408'

In [243]:
# pass_table_18.find('tbody').find_all('tr')[31]

In [245]:
driver.find_element_by_link_text('2009').click()

In [246]:
soup_09 = BeautifulSoup(driver.page_source)

In [247]:
AFC_table = soup_09.find('table', {'id': 'AFC'})

In [253]:
AFC_table.find_all('tr')[2]

<tr data-row="1"><th class="left" csk="1" data-stat="team" scope="row"><a href="/teams/nwe/2009.htm">New England Patriots</a>*</th><td class="right" data-stat="wins">10</td><td class="right" data-stat="losses">6</td><td class="right" data-stat="win_loss_perc">.625</td><td class="right" data-stat="points">427</td><td class="right" data-stat="points_opp">285</td><td class="right" data-stat="points_diff">142</td><td class="right" data-stat="mov">8.9</td><td class="right" data-stat="sos_total">2.3</td><td class="right" data-stat="srs_total">11.2</td><td class="right" data-stat="srs_offense">6.7</td><td class="right" data-stat="srs_defense">4.5</td></tr>

### Passing Table Template

In [184]:
df = pd.DataFrame(columns=
                  ['team','year','game','comp','attempts','comp_perc','pass_yards','pass_tds','pass_td_perc',
                   'int','int_perc','pass_long','pass_y/a','y/c','pass_y/g','QB_rate','sacks','sack_yds',
                   'sack_perc','qb_comebacks','qb_gwd','pass_exp'])

for row in pass_table_18.find('tbody').find_all('tr')[1:]:
    team = row.find('td').text
    year = 2018
    game = row.find('td', {'data-stat': 'g'}).text
    comp = row.find('td', {'data-stat': 'pass_cmp'}).text
    attempts = row.find('td', {'data-stat': 'pass_att'}).text
    comp_perc = row.find('td', {'data-stat': 'pass_cmp_perc'}).text
    pass_yards = row.find('td', {'data-stat': 'pass_yds'}).text
    pass_tds = row.find('td', {'data-stat': 'pass_td'}).text
    pass_td_perc = row.find('td', {'data-stat': 'pass_td_perc'}).text
    intercept = row.find('td', {'data-stat': 'pass_int'}).text
    int_perc = row.find('td', {'data-stat': 'pass_int_perc'}).text
    pass_long = row.find('td', {'data-stat': 'pass_long'}).text
    pass_ya = row.find('td', {'data-stat': 'pass_yds_per_att'}).text
    yc = row.find('td', {'data-stat': 'pass_yds_per_cmp'}).text
    pass_yg = row.find('td', {'data-stat': 'pass_yds_per_g'}).text
    qb_rate = row.find('td', {'data-stat': 'pass_rating'}).text
    sacks = row.find('td', {'data-stat': 'pass_sacked'}).text
    sack_yds = row.find('td', {'data-stat': 'pass_sacked_yds'}).text
    sack_perc = row.find('td', {'data-stat': 'pass_sacked_perc'}).text
    qb_cmbk = row.find('td', {'data-stat': 'comebacks'}).text
    qb_gwd = row.find('td', {'data-stat': 'gwd'}).text
    pass_exp = row.find('td', {'data-stat': 'exp_pts_pass'}).text
    
    df.loc[len(df)] = [team, year, game, comp, attempts, comp_perc,
                      pass_yards, pass_tds, pass_td_perc, intercept,
                      int_perc, pass_long, pass_ya, yc, pass_yg,
                      qb_rate, sacks, sack_yds, sack_perc, qb_cmbk, qb_gwd, pass_exp]
    
    sleep(1)

In [185]:
df

,team,year,game,comp,attempts,comp_perc,pass_yards,pass_tds,pass_td_perc,int,...,pass_y/a,y/c,pass_y/g,QB_rate,sacks,sack_yds,sack_perc,qb_comebacks,qb_gwd,pass_exp
0,Tampa Bay Buccaneers,2018,16,408,625,65.3,5125,36,5.8,26,...,8.6,13.1,320.3,94.1,41,233,6.2,0,1,159.05
1,Pittsburgh Steelers,2018,16,459,689,66.6,5008,35,5.1,17,...,7.5,11.3,313.0,95.5,24,166,3.4,2,3,161.94
2,Kansas City Chiefs,2018,16,385,583,66.0,4955,50,8.6,12,...,8.8,13.3,309.7,113.8,26,171,4.3,2,2,266.71
3,Atlanta Falcons,2018,16,428,617,69.4,4653,36,5.8,7,...,8.0,11.6,290.8,108.0,42,296,6.4,1,1,180.60
4,Los Angeles Rams,2018,16,368,568,64.8,4507,32,5.6,12,...,8.3,12.9,281.7,100.7,33,223,5.5,4,4,173.99
5,Indianapolis Colts,2018,16,432,644,67.1,4461,39,6.1,15,...,7.1,10.6,278.8,98.2,18,134,2.7,3,3,148.05
6,Philadelphia Eagles,2018,16,422,599,70.5,4275,29,4.8,11,...,7.6,10.7,267.2,100.7,40,249,6.3,4,4,129.50
7,New England Patriots,2018,16,378,574,65.9,4258,29,5.1,11,...,7.7,11.7,266.1,97.8,21,147,3.5,1,2,194.27
8,Green Bay Packers,2018,16,392,640,61.3,4238,25,3.9,4,...,7.2,11.8,264.9,93.7,53,391,7.6,3,3,71.30
9,Los Angeles Chargers,2018,16,348,512,68.0,4089,32,6.3,12,...,8.4,12.4,255.6,104.9,34,227,6.2,3,3,168.12
10,New York Giants,2018,16,382,583,65.5,4047,23,3.9,12,...,7.6,11.5,252.9,92.7,47,358,7.5,1,2,77.66
11,New Orleans Saints,2018,16,381,519,73.4,4042,33,6.4,7,...,8.0,11.0,252.6,112.3,20,132,3.7,6,7,215.12
12,Minnesota Vikings,2018,16,425,606,70.1,4036,30,5.0,10,...,7.1,10.1,252.3,99.7,40,262,6.2,1,0,52.77
13,Cleveland Browns,2018,16,353,574,61.5,4007,29,5.1,17,...,7.4,12.1,250.4,88.8,38,254,6.2,4,4,48.28
14,San Francisco 49ers,2018,16,331,532,62.2,3867,26,4.9,20,...,8.0,12.8,241.7,87.8,48,380,8.3,0,1,61.30
15,Carolina Panthers,2018,16,378,563,67.1,3836,28,5.0,16,...,7.2,10.8,239.8,92.9,32,235,5.4,2,2,80.29
16,Houston Texans,2018,16,345,506,68.2,3781,26,5.1,9,...,8.2,12.1,236.3,102.9,62,384,10.9,5,5,109.94
17,Oakland Raiders,2018,16,382,556,68.7,3751,19,3.4,10,...,7.3,10.6,234.4,93.6,52,306,8.6,3,3,30.85
18,Denver Broncos,2018,16,367,588,62.4,3695,19,3.2,15,...,6.7,10.7,230.9,82.1,34,235,5.5,3,4,26.00
19,Detroit Lions,2018,16,375,574,65.3,3576,22,3.8,12,...,6.7,10.3,223.5,88.5,41,268,6.7,0,1,67.19
20,Chicago Bears,2018,16,344,512,67.2,3564,28,5.5,14,...,7.3,10.9,222.8,95.4,33,183,6.1,2,2,97.62
21,Baltimore Ravens,2018,16,334,556,60.1,3558,18,3.2,9,...,6.7,11.1,222.4,84.0,32,150,5.4,0,1,61.49
22,Dallas Cowboys,2018,16,356,527,67.6,3538,22,4.2,8,...,7.4,10.9,221.1,96.7,56,347,9.6,3,5,64.95
23,Cincinnati Bengals,2018,16,331,542,61.1,3290,27,5.0,13,...,6.6,10.8,205.6,87.0,37,279,6.4,3,4,65.06
24,New York Jets,2018,16,299,524,57.1,3165,18,3.4,19,...,6.5,11.4,197.8,73.0,37,239,6.6,1,1,-40.27
25,Jacksonville Jaguars,2018,16,329,536,61.4,3109,15,2.8,13,...,6.4,10.4,194.3,79.1,53,322,9.0,0,1,-65.36
26,Seattle Seahawks,2018,16,280,427,65.6,3093,35,8.2,7,...,8.1,12.3,193.3,110.9,51,355,10.7,2,4,114.50
27,Washington Redskins,2018,16,311,509,61.1,3021,16,3.1,15,...,6.5,10.6,188.8,78.1,44,266,8.0,1,1,-24.87
28,Tennessee Titans,2018,16,293,437,67.0,2975,16,3.7,12,...,7.4,11.1,185.9,89.8,47,280,9.7,4,5,16.34
29,Miami Dolphins,2018,16,292,455,64.2,2900,26,5.7,13,...,7.3,11.3,181.3,93.0,52,409,10.3,4,4,-19.71
30,Buffalo Bills,2018,16,271,499,54.3,2794,13,2.6,23,...,6.2,11.4,174.6,62.6,41,288,7.6,2,3,-88.45
31,Arizona Cardinals,2018,16,283,495,57.2,2523,15,3.0,18,...,5.8,10.2,157.7,69.0,52,361,9.5,1,2,-106.25

### Master Team Scrapper per Year

In [355]:
# Finding the table on the page that contains all of the years in the NFL.
years_table = soup.find('table', {'id': 'years'})

In [356]:
# Obtaining each numerical year
years_list = []

for row in years_table.find_all('tr')[1:52]:
    if row.find('th').text == 'Year':
        pass
    else:
        year = row.find('th').text
        years_list.append(year)

In [357]:
len(years_list)

50

In [358]:
years_list[49]

'1970'

This loop collects all of the years in the NFL I would like to collect data from.

In [339]:
# Looping through each year page
# Empty containeer for each team dictionary
teams = []

# Initiating DataFrame for passing stats with column names
pass_df = pd.DataFrame(columns=
                  ['team','year','game','comp','attempts','comp_perc','pass_yards','pass_tds','pass_td_perc',
                   'int','int_perc','pass_long','pass_y/a','y/c','pass_y/g','QB_rate','sacks','sack_yds',
                   'sack_perc','qb_comebacks','qb_gwd','pass_exp'])

# Initiating DataFrame for rushing stats with column names




start = datetime.now()
for year in years_list[5:]: # Looping through each year from current year (2019) to 1970.
    print(year)
    # Link to specific year for selenium to click on
#     year_link = driver.find_element_by_link_text(year)
#     driver.implicitly_wait(5)
#     year_link.click()

    # using the original url combined with the year to access the specific year
    driver.get(surl + year)
    
    # creating soup for current year in loop
    year_soup = BeautifulSoup(driver.page_source)
#     print(year_soup)
    
    # Seek AFC Table and collect Data
    AFC_table = year_soup.find('div', {'id': 'div_AFC'})
#     print(AFC_table.find('tr'))
#     AFC_table = year_soup.find('table', {'id': 'AFC'})
    sleep(3)
    
    # looping throuh each row in the current year AFC table and collecting data
    try:
        for row in AFC_table.find_all('tr')[1:]:
            team = {}
            tm = row.find('th')
            wins = row.find('td', {'data-stat': 'wins'})
            loss = row.find('td', {'data-stat': 'losses'})
            tie = row.find('td', {'data-stat': 'ties'})
            wlp = row.find('td', {'data-stat': 'win_loss_perc'})
            pts = row.find('td', {'data-stat': 'points'})
            ptsA = row.find('td', {'data-stat': 'points_opp'})
            dpts = row.find('td', {'data-stat': 'points_diff'})
            moV = row.find('td', {'data-stat': 'mov'})
            sos = row.find('td', {'data-stat': 'sos_total'})
            srs = row.find('td', {'data-stat': 'srs_total'})
            osrs = row.find('td', {'data-stat': 'srs_offense'})
            dsrs = row.find('td', {'data-stat': 'srs_defense'})


            if tm:
                team['team'] = tm.text.replace('*','').replace('+','')
                team['year'] = year
            if wins:
                team['wins'] = wins.text
            if loss:
                team['losses'] = loss.text
            if tie:
                team['ties'] = tie.text
            if wlp:
                team['win_loss_perc'] = wlp.text
            if pts:
                team['points_scored'] = pts.text
            if ptsA:
                team['opp_points'] = ptsA.text
            if dpts:
                team['points_diff'] = dpts.text
            if moV:
                team['margin_of_victory'] = moV.text
            if sos:
                team['SoS'] = sos.text 
            if srs:
                team['SRS'] = srs.text
            if osrs:
                team['OSRS'] = osrs.text
            if dsrs:
                team['DSRS'] = dsrs.text


            else:
                continue

#             sleep(1)

            # appending created dictionary of current year to teams list
            teams.append(team)
    except:
        print(f"error with year: {year} AFC table")
    
    # Seek NFC Table and collect Data
#     NFC_table = year_soup.find('table', {'id': 'NFC'})
    NFC_table = year_soup.find('div', {'id': 'div_NFC'})
    sleep(3)
    
    # looping throuh each row in the current year NFC table and collecting data
    try:
        for row in NFC_table.find_all('tr')[1:]:
            team = {}
            tm = row.find('th')
            wins = row.find('td', {'data-stat': 'wins'})
            loss = row.find('td', {'data-stat': 'losses'})
            tie = row.find('td', {'data-stat': 'ties'})
            wlp = row.find('td', {'data-stat': 'win_loss_perc'})
            pts = row.find('td', {'data-stat': 'points'})
            ptsA = row.find('td', {'data-stat': 'points_opp'})
            dpts = row.find('td', {'data-stat': 'points_diff'})
            moV = row.find('td', {'data-stat': 'mov'})
            sos = row.find('td', {'data-stat': 'sos_total'})
            srs = row.find('td', {'data-stat': 'srs_total'})
            osrs = row.find('td', {'data-stat': 'srs_offense'})
            dsrs = row.find('td', {'data-stat': 'srs_defense'})

            if tm:
                team['team'] = tm.text.replace('*','').replace('+','')
                team['year'] = year
            if wins:
                team['wins'] = wins.text
            if loss:
                team['losses'] = loss.text
            if tie:
                team['ties'] = tie.text
            if wlp:
                team['win_loss_perc'] = wlp.text
            if pts:
                team['points_scored'] = pts.text
            if ptsA:
                team['opp_points'] = ptsA.text
            if dpts:
                team['points_diff'] = dpts.text
            if moV:
                team['margin_of_victory'] = moV.text
            if sos:
                team['SoS'] = sos.text 
            if srs:
                team['SRS'] = srs.text
            if osrs:
                team['OSRS'] = osrs.text
            if dsrs:
                team['DSRS'] = dsrs.text


            else:
                continue

#             sleep(1)

            # appending created dictionary of current year to teams list
            teams.append(team)
    except:
        print(f"error with year: {year} NFC Table")
        
    # Seek the passing table in the current NFL year.
    pass_table = year_soup.find('table', {'id': 'passing'})
    
    # Looping through each row of the current year passing table and collecting data
    for row in pass_table.find('tbody').find_all('tr'):
        team = row.find('td').text
        year = year
        game = row.find('td', {'data-stat': 'g'}).text
        comp = row.find('td', {'data-stat': 'pass_cmp'}).text
        attempts = row.find('td', {'data-stat': 'pass_att'}).text
        comp_perc = row.find('td', {'data-stat': 'pass_cmp_perc'}).text
        pass_yards = row.find('td', {'data-stat': 'pass_yds'}).text
        pass_tds = row.find('td', {'data-stat': 'pass_td'}).text
        pass_td_perc = row.find('td', {'data-stat': 'pass_td_perc'}).text
        intercept = row.find('td', {'data-stat': 'pass_int'}).text
        int_perc = row.find('td', {'data-stat': 'pass_int_perc'}).text
        pass_long = row.find('td', {'data-stat': 'pass_long'}).text
        pass_ya = row.find('td', {'data-stat': 'pass_yds_per_att'}).text
        yc = row.find('td', {'data-stat': 'pass_yds_per_cmp'}).text
        pass_yg = row.find('td', {'data-stat': 'pass_yds_per_g'}).text
        qb_rate = row.find('td', {'data-stat': 'pass_rating'}).text
        sacks = row.find('td', {'data-stat': 'pass_sacked'}).text
        sack_yds = row.find('td', {'data-stat': 'pass_sacked_yds'}).text
        sack_perc = row.find('td', {'data-stat': 'pass_sacked_perc'}).text
        qb_cmbk = row.find('td', {'data-stat': 'comebacks'}).text
        qb_gwd = row.find('td', {'data-stat': 'gwd'}).text
        try:
            pass_exp = row.find('td', {'data-stat': 'exp_pts_pass'}).text
        except:
            pass_exp = None
        
#         sleep(1)
        
        # adding each row of stats to the passing DataFrame
        pass_df.loc[len(pass_df)] = [team, year, game, comp, attempts, comp_perc,
                      pass_yards, pass_tds, pass_td_perc, intercept,
                      int_perc, pass_long, pass_ya, yc, pass_yg,
                      qb_rate, sacks, sack_yds, sack_perc, qb_cmbk, qb_gwd, pass_exp]
    
    # Seek the rushing table in the current NFL year.
    
    # Looping through each row of the current year rushing table and collecting data
    
    sleep(10)
    
    # Link to access the overall "seasons" page
#     seasons_button = driver.find_element_by_link_text('Seasons')
#     driver.implicitly_wait(3)
#     seasons_button.click()

    
team_df = pd.DataFrame(teams)
stop = datetime.now()
print(f'The total time passed during scrape (hh:mm:ss:ms) is: {stop - start}')

2014
2013
2012
2011
2010
2009
2008
2007
2006
2005
2004
2003
2002
2001
2000
1999
1998
1997
1996
1995
1994
1993
1992
1991
1990
1989
1988
1987
1986
1985
1984
1983
1982
1981
1980
1979
1978
1977
1976
1975
1974
1973
1972
1971
1970
The total time passed during scrape (hh:mm:ss:ms) is: 0:57:28.662571

In [340]:
# Resulting team DataFrame
print(team_df.shape)
team_df.head()

(1317, 14)

,team,year,wins,losses,ties,win_loss_perc,points_scored,opp_points,points_diff,margin_of_victory,SoS,SRS,OSRS,DSRS
0,New England Patriots,2014,12,4,0,.750,468,313,155,9.7,1.3,10.9,7.5,3.5
1,Buffalo Bills,2014,9,7,0,.563,343,289,54,3.4,1.6,4.9,-0.4,5.3
2,Miami Dolphins,2014,8,8,0,.500,388,373,15,0.9,1.6,2.6,2.9,-0.4
3,New York Jets,2014,4,12,0,.250,283,401,-118,-7.4,2.3,-5.0,-4.0,-1.0
4,Pittsburgh Steelers,2014,11,5,0,.688,436,368,68,4.3,-2.0,2.2,4.4,-2.1

In [341]:
# Resulting passing DataFrame
print(pass_df.shape)
pass_df.head()

(1317, 22)

,team,year,game,comp,attempts,comp_perc,pass_yards,pass_tds,pass_td_perc,int,...,pass_y/a,y/c,pass_y/g,QB_rate,sacks,sack_yds,sack_perc,qb_comebacks,qb_gwd,pass_exp
0,Indianapolis Colts,2014,16,410,661,62.0,4894,42,6.4,16,...,7.7,12.3,305.9,96.8,29,168,4.2,1,1,144.43
1,Pittsburgh Steelers,2014,16,411,612,67.2,4825,33,5.4,10,...,8.2,12.2,301.6,103.2,33,172,5.1,2,3,180.29
2,New Orleans Saints,2014,16,456,659,69.2,4764,33,5.0,17,...,7.5,10.9,297.8,97.0,30,188,4.4,2,2,147.22
3,Denver Broncos,2014,16,399,607,65.7,4661,40,6.6,15,...,7.9,12.0,291.3,101.3,17,118,2.7,1,1,162.22
4,Atlanta Falcons,2014,16,418,632,66.1,4553,28,4.4,15,...,7.5,11.4,284.6,93.4,31,205,4.7,3,3,93.29

In [342]:
team_df['team'].value_counts().tail()

Houston Texans         13
Los Angeles Raiders    13
Phoenix Cardinals       6
Tennessee Oilers        2
Boston Patriots         1
Name: team, dtype: int64

In [343]:
pass_df['year'].value_counts().tail()

1972    26
1975    26
1973    26
1974    26
1970    26
Name: year, dtype: int64

In [344]:
# Saving remainder of years
team_df.to_csv('./teams_2014_1970.csv', index=False)

In [345]:
# Saving remainder of years
pass_df.to_csv('./pass_2014_1970.csv', index=False)

In [337]:
# Saving first 5 years scrape
# team_df.to_csv('./teams_2019_2015.csv', index=False)

In [336]:
# Saving first 5 years scrape
# pass_df.to_csv('./pass_2019_2015.csv', index=False)

I attempted my inital scrapper for all years in 2 seperate chunks so I saved them as csvs. I will later combined them all together in one code.

### Gathering final data from the Rushing tables in each year

In [361]:
rush_df = pd.DataFrame(columns=
                  ['team','year','game','rush_att','rush_yards','rush_tds','rush_long',
                   'rush_y/a','rush_y/g','fumbles','rush_exp'])

start = datetime.now()
for year in years_list: # Looping through each year from current year (2019) to 1970.
    print(year)

    # using the original url combined with the year to access the specific year
    driver.get(surl + year)
    
    # creating soup for current year in loop
    year_soup = BeautifulSoup(driver.page_source)
    
    # Seek the passing table in the current NFL year.
    rush_table = year_soup.find('table', {'id': 'rushing'})
    
    # Looping through each row of the current year passing table and collecting data
    for row in rush_table.find('tbody').find_all('tr'):
        team = row.find('td').text
        year = year
        game = row.find('td', {'data-stat': 'g'}).text
        attempts = row.find('td', {'data-stat': 'rush_att'}).text
        rush_yards = row.find('td', {'data-stat': 'rush_yds'}).text
        rush_tds = row.find('td', {'data-stat': 'rush_td'}).text
        rush_long = row.find('td', {'data-stat': 'rush_long'}).text
        rush_ya = row.find('td', {'data-stat': 'rush_yds_per_att'}).text
        rush_yg = row.find('td', {'data-stat': 'rush_yds_per_g'}).text
        fumb = row.find('td', {'data-stat': 'fumbles'}).text
        try:
            rush_exp = row.find('td', {'data-stat': 'exp_pts_rush'}).text
        except:
            rush_exp = None
        
        
        # adding each row of stats to the passing DataFrame
        rush_df.loc[len(rush_df)] = [team, year, game, attempts, rush_yards, rush_tds, 
                                     rush_long, rush_ya, rush_yg, fumb, rush_exp]
        
    sleep(10)
        
stop = datetime.now()
print(f'The total time passed during rushing stats scrape (hh:mm:ss:ms) is: {stop - start}')

2019
2018
2017
2016
2015
2014
2013
2012
2011
2010
2009
2008
2007
2006
2005
2004
2003
2002
2001
2000
1999
1998
1997
1996
1995
1994
1993
1992
1991
1990
1989
1988
1987
1986
1985
1984
1983
1982
1981
1980
1979
1978
1977
1976
1975
1974
1973
1972
1971
1970
The total time passed during rushing stats scrape (hh:mm:ss:ms) is: 0:09:33.726971

In [362]:
print(rush_df.shape)
rush_df.head()

(1477, 11)

,team,year,game,rush_att,rush_yards,rush_tds,rush_long,rush_y/a,rush_y/g,fumbles,rush_exp
0,Baltimore Ravens,2019,9,322,1775,15,60,5.5,197.2,10,54.60
1,Minnesota Vikings,2019,10,326,1530,13,75,4.7,153.0,19,8.27
2,San Francisco 49ers,2019,9,330,1456,13,83,4.4,161.8,10,-19.33
3,Seattle Seahawks,2019,10,307,1332,9,59,4.3,133.2,18,-32.34
4,Houston Texans,2019,9,259,1285,10,58,5.0,142.8,13,16.73

In [363]:
rush_df.to_csv('./rush_stats.csv', index=False)